In [4]:
import os

print(os.listdir("/content"))

['.config', 'online_retail_II.xlsx', '.ipynb_checkpoints', 'sample_data']

In [5]:
!pip install openpyxl -q

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_path = "/content/online_retail_II.xlsx"

df = pd.read_excel(file_path, engine="openpyxl")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (525461, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [7]:
import os

print(os.path.getsize("/content/online_retail_II.xlsx"))

45622278

In [8]:
print("Columns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Columns:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

Data types:
Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
dtype: object

Missing values:
Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

Duplicate rows: 6865

In [9]:
print("Dataset shape:", df.shape)
print("Total records:", len(df))

Dataset shape: (525461, 8)
Total records: 525461

In [10]:
print("Unique invoices:", df['Invoice'].nunique())
print("Unique products:", df['StockCode'].nunique())
print("Unique customers:", df['Customer ID'].nunique())
print("Unique countries:", df['Country'].nunique())

Unique invoices: 28816
Unique products: 4632
Unique customers: 4383
Unique countries: 40

In [11]:
print("Invoices starting with C:",
      df['Invoice'].astype(str).str.startswith('C').sum())

Invoices starting with C: 10206

In [12]:
print("Quantity statistics:")
display(df['Quantity'].describe())

print("\nPrice statistics:")
display(df['Price'].describe())

Quantity statistics:

count    525461.000000
mean         10.337667
std         107.424110
min       -9600.000000
25%           1.000000
50%           3.000000
75%          10.000000
max       19152.000000
Name: Quantity, dtype: float64

Price statistics:

count    525461.000000
mean          4.688834
std         146.126914
min      -53594.360000
25%           1.250000
50%           2.100000
75%           4.210000
max       25111.090000
Name: Price, dtype: float64

In [13]:
print("Negative quantities:", (df['Quantity'] < 0).sum())
print("Zero quantities:", (df['Quantity'] == 0).sum())

print("Negative prices:", (df['Price'] < 0).sum())
print("Zero prices:", (df['Price'] == 0).sum())

Negative quantities: 12326
Zero quantities: 0
Negative prices: 3
Zero prices: 3687

In [14]:
df[df['Price'] < 0][
    ['Invoice', 'StockCode', 'Description', 'Quantity',
     'InvoiceDate', 'Price', 'Customer ID', 'Country']
]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom

In [15]:
df[df['Price'] == 0][
    ['Invoice', 'StockCode', 'Description', 'Quantity',
     'InvoiceDate', 'Price', 'Customer ID', 'Country']
].head(30)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4538,489820,21133,invcd as 84879?,-720,2009-12-02 13:23:00,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom
4674,489825,22076,6 RIBBONS EMPIRE,12,2009-12-02 13:34:00,0.0,16126.0,United Kingdom
5904,489861,DOT,DOTCOM POSTAGE,1,2009-12-02 14:50:00,0.0,NaN,United Kingdom
6378,489882,35751C,NaN,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom
6555,489898,79323G,NaN,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom
6556,489899,79323GR,sold as gold,-954,2009-12-03 09:41:00,0.0,NaN,United Kingdom
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom
6781,489998,48185,DOOR MAT FAIRY CAKE,2,2009-12-03 11:19:00,0.0,15658.0,United Kingdom
6911,490007,84347,21494,-720,2009-12-03 12:09:00,0.0,NaN,United Kingdom
7204,490015,21982,NaN,467,2009-12-03 12:29:00,0.0,NaN,United Kingdom
7205,490016,21982,NaN,-1012,2009-12-03 12:30:00,0.0,NaN,United Kingdom
7559,490055,20620,NaN,-25,2009-12-03 13:22:00,0.0,NaN,United Kingdom
8553,490084,85064,NaN,-89,2009-12-03 15:37:00,0.0,NaN,United Kingdom
9249,490123,84508B,NaN,184,2009-12-03 18:08:00,0.0,NaN,United Kingdom
9308,490130,21493,lost?,-600,2009-12-03 18:28:00,0.0,NaN,United Kingdom
9667,490146,21558,NaN,-169,2009-12-04 09:29:00,0.0,NaN,United Kingdom
10236,490150,84347,NaN,80,2009-12-04 09:44:00,0.0,NaN,United Kingdom
10508,490165,21493,NaN,-106,2009-12-04 11:32:00,0.0,NaN,United Kingdom

In [16]:
# Show some duplicate records
duplicates = df[df.duplicated(keep=False)]

print("Total duplicate rows:", len(duplicates))

display(
    duplicates.sort_values(
        ['Invoice', 'StockCode', 'InvoiceDate']
    ).head(20)
)

Total duplicate rows: 13283

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom

In [17]:
# Compare exact duplicates with duplicate groups
exact_duplicates = df.duplicated(keep=False)

print("Rows involved in duplicate groups:", exact_duplicates.sum())
print("Unique duplicate row patterns:", df[df.duplicated()].shape[0])

# Show one exact duplicate pattern
display(
    df[df.duplicated(keep=False)]
    .sort_values(['Invoice', 'StockCode', 'InvoiceDate'])
    .head(10)
)

Rows involved in duplicate groups: 13283
Unique duplicate row patterns: 6865

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom

In [18]:
# Remove exact duplicate rows
df_clean = df.drop_duplicates().copy()

print("Original rows:", len(df))
print("Rows after removing exact duplicates:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))

Original rows: 525461
Rows after removing exact duplicates: 518596
Rows removed: 6865

In [19]:
# Check missing values after duplicate removal
missing = df_clean.isnull().sum()

print("Missing values:")
display(missing)

print("\nMissing percentage:")
display((missing / len(df_clean) * 100).round(2))

Missing values:

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107833
Country             0
dtype: int64

Missing percentage:

Invoice         0.00
StockCode       0.00
Description     0.56
Quantity        0.00
InvoiceDate     0.00
Price           0.00
Customer ID    20.79
Country         0.00
dtype: float64

In [20]:
# Compare transactions with and without Customer ID

missing_customer = df_clean[df_clean['Customer ID'].isna()]
known_customer = df_clean[df_clean['Customer ID'].notna()]

print("Rows with missing Customer ID:", len(missing_customer))
print("Rows with Customer ID:", len(known_customer))

print("\nInvoice types with missing Customer ID:")
print(missing_customer['Invoice'].astype(str).str.startswith('C').value_counts())

print("\nInvoice types with known Customer ID:")
print(known_customer['Invoice'].astype(str).str.startswith('C').value_counts())

Rows with missing Customer ID: 107833
Rows with Customer ID: 410763

Invoice types with missing Customer ID:
Invoice
False    107467
True        366
Name: count, dtype: int64

Invoice types with known Customer ID:
Invoice
False    400947
True       9816
Name: count, dtype: int64

In [21]:
# Create transaction value
df_clean['TotalAmount'] = df_clean['Quantity'] * df_clean['Price']

# Compare missing vs known Customer IDs
customer_id_summary = df_clean.groupby(
    df_clean['Customer ID'].isna()
)['TotalAmount'].agg(['count', 'sum', 'mean'])

customer_id_summary.index = ['Customer ID Present', 'Customer ID Missing']

display(customer_id_summary)

                      count          sum       mean
Customer ID Present  410763  8314855.584  20.242465
Customer ID Missing  107833  1190919.980  11.044114

In [22]:
# Investigate rows with missing Description

missing_description = df_clean[df_clean['Description'].isna()]

print("Rows with missing Description:", len(missing_description))
print("Total transaction value:", missing_description['TotalAmount'].sum())

print("\nQuantity summary:")
display(missing_description['Quantity'].describe())

print("\nPrice summary:")
display(missing_description['Price'].describe())

print("\nSample rows:")
display(missing_description.head(20))

Rows with missing Description: 2928
Total transaction value: 0.0

Quantity summary:

count    2928.000000
mean      -21.186475
std       599.532127
min     -9600.000000
25%       -30.000000
50%        -4.500000
75%         3.000000
max      9600.000000
Name: Quantity, dtype: float64

Price summary:

count    2928.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: Price, dtype: float64

Sample rows:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalAmount
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom,-0.0
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom,-0.0
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom,0.0
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom,0.0
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom,-0.0
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom,-0.0
6378,489882,35751C,NaN,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom,0.0
6555,489898,79323G,NaN,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom,0.0
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom,-0.0
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom,0.0
7204,490015,21982,NaN,467,2009-12-03 12:29:00,0.0,NaN,United Kingdom,0.0
7205,490016,21982,NaN,-1012,2009-12-03 12:30:00,0.0,NaN,United Kingdom,-0.0
7559,490055,20620,NaN,-25,2009-12-03 13:22:00,0.0,NaN,United Kingdom,-0.0
8553,490084,85064,NaN,-89,2009-12-03 15:37:00,0.0,NaN,United Kingdom,-0.0
9249,490123,84508B,NaN,184,2009-12-03 18:08:00,0.0,NaN,United Kingdom,0.0
9667,490146,21558,NaN,-169,2009-12-04 09:29:00,0.0,NaN,United Kingdom,-0.0
10236,490150,84347,NaN,80,2009-12-04 09:44:00,0.0,NaN,United Kingdom,0.0
10508,490165,21493,NaN,-106,2009-12-04 11:32:00,0.0,NaN,United Kingdom,-0.0
11973,490354,21489,NaN,-23,2009-12-04 16:39:00,0.0,NaN,United Kingdom,-0.0
12237,490379,21490,NaN,-44,2009-12-05 13:26:00,0.0,NaN,United Kingdom,-0.0

In [23]:
# Remove rows with missing Description and zero Price
before = len(df_clean)

df_clean = df_clean[
    ~(df_clean['Description'].isna() & (df_clean['Price'] == 0))
].copy()

after = len(df_clean)

print("Rows before:", before)
print("Rows removed:", before - after)
print("Rows after:", after)

print("\nRemaining missing Description values:",
      df_clean['Description'].isna().sum())

Rows before: 518596
Rows removed: 2928
Rows after: 515668

Remaining missing Description values: 0

In [24]:
# Check positive vs negative quantity transactions

positive_qty = (df_clean['Quantity'] > 0).sum()
negative_qty = (df_clean['Quantity'] < 0).sum()

print("Positive quantity rows:", positive_qty)
print("Negative quantity rows:", negative_qty)

print("\nNegative quantity percentage:",
      round(negative_qty / len(df_clean) * 100, 2), "%")

print("\nNegative quantity transaction value:",
      df_clean.loc[df_clean['Quantity'] < 0, 'TotalAmount'].sum())

Positive quantity rows: 505193
Negative quantity rows: 10475

Negative quantity percentage: 2.03 %

Negative quantity transaction value: -629808.65

In [25]:
# Check cancellation invoices among negative quantities

negative_rows = df_clean[df_clean['Quantity'] < 0].copy()

negative_cancellations = (
    negative_rows['Invoice']
    .astype(str)
    .str.startswith('C')
    .sum()
)

negative_other = len(negative_rows) - negative_cancellations

print("Negative quantity rows:", len(negative_rows))
print("Negative rows with cancellation invoice (C):", negative_cancellations)
print("Negative rows without C invoice:", negative_other)

print("\nCancellation percentage among negative rows:",
      round(negative_cancellations / len(negative_rows) * 100, 2), "%")

Negative quantity rows: 10475
Negative rows with cancellation invoice (C): 10181
Negative rows without C invoice: 294

Cancellation percentage among negative rows: 97.19 %

In [26]:
# Investigate negative quantities that are NOT cancellation invoices

other_negative = df_clean[
    (df_clean['Quantity'] < 0) &
    (~df_clean['Invoice'].astype(str).str.startswith('C'))
].copy()

print("Rows:", len(other_negative))
print("Total value:", other_negative['TotalAmount'].sum())

print("\nTop descriptions:")
display(other_negative['Description'].value_counts().head(20))

print("\nSample records:")
display(other_negative.head(20))

Rows: 294
Total value: 0.0

Top descriptions:

Description
?               42
damages         39
damaged         36
missing         24
dotcom           6
given away       6
checked          5
smashed          5
Damages          4
crushed          4
ebay sales       4
MIA              4
No Stock         3
check            3
Damaged          3
counted          3
gone             2
discoloured      2
broken zips      2
Dotcom sales     2
Name: count, dtype: int64

Sample records:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalAmount
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom,-0.0
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom,-0.0
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom,-0.0
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom,-0.0
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom,-0.0
4538,489820,21133,invcd as 84879?,-720,2009-12-02 13:23:00,0.0,NaN,United Kingdom,-0.0
6556,489899,79323GR,sold as gold,-954,2009-12-03 09:41:00,0.0,NaN,United Kingdom,-0.0
6911,490007,84347,21494,-720,2009-12-03 12:09:00,0.0,NaN,United Kingdom,-0.0
9308,490130,21493,lost?,-600,2009-12-03 18:28:00,0.0,NaN,United Kingdom,-0.0
17427,490765,21450,damaged,-31,2009-12-08 10:59:00,0.0,NaN,United Kingdom,-0.0
17428,490766,51008,wet,-200,2009-12-08 11:06:00,0.0,NaN,United Kingdom,-0.0
20970,491065,84855,MIA,-108,2009-12-09 11:59:00,0.0,NaN,United Kingdom,-0.0
28111,491732,79030A,smashed,-350,2009-12-14 10:00:00,0.0,NaN,United Kingdom,-0.0
32104,491972,21100,bad quality,-76,2009-12-14 18:43:00,0.0,NaN,United Kingdom,-0.0
39399,492719,48173C,MIA,-9,2009-12-18 10:49:00,0.0,NaN,United Kingdom,-0.0
41347,492788,72739B,discoloured,-70,2009-12-18 17:45:00,0.0,NaN,United Kingdom,-0.0
41349,492787,85112,damaged,-38,2009-12-18 17:45:00,0.0,NaN,United Kingdom,-0.0
41350,492790,37503,damaged,-19,2009-12-18 17:46:00,0.0,NaN,United Kingdom,-0.0
41351,492789,72739C,discoloured,-64,2009-12-18 17:46:00,0.0,NaN,United Kingdom,-0.0
45960,493572,20714,missing,-450,2010-01-05 10:13:00,0.0,NaN,United Kingdom,-0.0

In [27]:
# Check negative-price records

negative_price = df_clean[df_clean['Price'] < 0]

print("Negative price rows:", len(negative_price))
print("Total value:", negative_price['TotalAmount'].sum())

display(negative_price)

Negative price rows: 3
Total value: -136552.02

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalAmount
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom,-53594.36
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom,-44031.79
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom,-38925.87

In [28]:
# Investigate all zero-price records
zero_price = df_clean[df_clean['Price'] == 0]

print("Zero-price rows:", len(zero_price))
print("Zero-price rows with positive quantity:",
      (zero_price['Quantity'] > 0).sum())
print("Zero-price rows with negative quantity:",
      (zero_price['Quantity'] < 0).sum())

print("\nDescriptions of zero-price rows:")
display(zero_price['Description'].value_counts().head(30))

Zero-price rows: 753
Zero-price rows with positive quantity: 459
Zero-price rows with negative quantity: 294

Descriptions of zero-price rows:

Description
?                                      45
damages                                39
damaged                                38
missing                                24
OWL DOORSTOP                            8
checked                                 8
PICNIC BASKET WICKER LARGE              7
POLYESTER FILLER PAD 45x45cm            7
dotcom                                  6
given away                              6
FLAG OF ST GEORGE CAR FLAG              6
IVORY KITCHEN SCALES                    5
POLYESTER FILLER PAD 40x40cm            5
WATERING CAN BLUE ELEPHANT              5
ENAMEL FIRE BUCKET CREAM                5
SMALL POPCORN HOLDER                    5
PICNIC BASKET WICKER SMALL              5
smashed                                 5
HEART OF WICKER SMALL                   5
AIRLINE BAG VINTAGE WORLD CHAMPION      5
ENAMEL WASH BOWL CREAM                  5
MILK PAN PINK RETROSPOT                 4
RED RETROSPOT STORAGE JAR               4
crushed                                 4
HANGING METAL STAR LANTERN              4
ebay sales                              4
DOOR MAT UNION JACK GUNS AND ROSES      4
BOX OF 24 COCKTAIL PARASOLS             4
ZINC WILLIE WINKIE  CANDLE STICK        4
temp                                    4
Name: count, dtype: int64

In [29]:
# Create sales-analysis dataset
# Exclude:
# 1. Negative-price bad-debt adjustments
# 2. Zero-price records

sales_df = df_clean[
    (df_clean['Price'] > 0) &
    (df_clean['Quantity'] != 0)
].copy()

print("Rows in cleaned dataset:", len(df_clean))
print("Rows in sales dataset:", len(sales_df))
print("Rows excluded:", len(df_clean) - len(sales_df))

print("\nRemaining negative prices:",
      (sales_df['Price'] < 0).sum())

print("Remaining zero prices:",
      (sales_df['Price'] == 0).sum())

Rows in cleaned dataset: 515668
Rows in sales dataset: 514912
Rows excluded: 756

Remaining negative prices: 0
Remaining zero prices: 0

In [30]:
# Calculate revenue for each transaction
sales_df['Revenue'] = sales_df['Quantity'] * sales_df['Price']

print("Total Revenue: £", round(sales_df['Revenue'].sum(), 2))

print("\nRevenue statistics:")
display(sales_df['Revenue'].describe())

Total Revenue: £ 9642327.58

Revenue statistics:

count    514912.000000
mean         18.726166
std         118.031066
min      -25111.090000
25%           3.800000
50%          10.080000
75%          17.700000
max       25111.090000
Name: Revenue, dtype: float64

In [31]:
# Create time-based analysis fields

sales_df['Year'] = sales_df['InvoiceDate'].dt.year
sales_df['Month'] = sales_df['InvoiceDate'].dt.month
sales_df['MonthName'] = sales_df['InvoiceDate'].dt.strftime('%b')
sales_df['YearMonth'] = sales_df['InvoiceDate'].dt.to_period('M').astype(str)

# Check the new fields
display(
    sales_df[
        ['InvoiceDate', 'Year', 'Month', 'MonthName', 'YearMonth']
    ].head(10)
)

print("\nYears:", sorted(sales_df['Year'].unique()))
print("Number of months:", sales_df['YearMonth'].nunique())

          InvoiceDate  Year  Month MonthName YearMonth
0 2009-12-01 07:45:00  2009     12       Dec   2009-12
1 2009-12-01 07:45:00  2009     12       Dec   2009-12
2 2009-12-01 07:45:00  2009     12       Dec   2009-12
3 2009-12-01 07:45:00  2009     12       Dec   2009-12
4 2009-12-01 07:45:00  2009     12       Dec   2009-12
5 2009-12-01 07:45:00  2009     12       Dec   2009-12
6 2009-12-01 07:45:00  2009     12       Dec   2009-12
7 2009-12-01 07:45:00  2009     12       Dec   2009-12
8 2009-12-01 07:46:00  2009     12       Dec   2009-12
9 2009-12-01 07:46:00  2009     12       Dec   2009-12

Years: [np.int32(2009), np.int32(2010)]
Number of months: 13

In [32]:
# Monthly revenue analysis

monthly_sales = (
    sales_df.groupby('YearMonth')['Revenue']
    .sum()
    .reset_index()
)

display(monthly_sales)

   YearMonth      Revenue
0    2009-12   796648.500
1    2010-01   622479.502
2    2010-02   531265.366
3    2010-03   763247.241
4    2010-04   641521.052
5    2010-05   613270.720
6    2010-06   677073.870
7    2010-07   617365.480
8    2010-08   654774.390
9    2010-09   851105.961
10   2010-10  1080611.480
11   2010-11  1416697.202
12   2010-12   376266.820

In [33]:
# Check the date range in each month

monthly_dates = (
    sales_df.groupby('YearMonth')['InvoiceDate']
    .agg(['min', 'max', 'count'])
    .reset_index()
)

display(monthly_dates)

   YearMonth                 min                 max  count
0    2009-12 2009-12-01 07:45:00 2009-12-23 16:58:00  44466
1    2010-01 2010-01-04 09:24:00 2010-01-31 16:02:00  31003
2    2010-02 2010-02-01 08:13:00 2010-02-28 16:16:00  28527
3    2010-03 2010-03-01 08:38:00 2010-03-31 17:31:00  40682
4    2010-04 2010-04-01 07:49:00 2010-04-30 17:33:00  33484
5    2010-05 2010-05-02 10:22:00 2010-05-30 15:58:00  34364
6    2010-06 2010-06-01 09:02:00 2010-06-30 17:38:00  39181
7    2010-07 2010-07-01 08:39:00 2010-07-30 17:08:00  32846
8    2010-08 2010-08-01 10:04:00 2010-08-31 17:44:00  32680
9    2010-09 2010-09-01 09:25:00 2010-09-30 20:11:00  41437
10   2010-10 2010-10-01 08:19:00 2010-10-31 16:26:00  57990
11   2010-11 2010-11-01 08:56:00 2010-11-30 19:35:00  76227
12   2010-12 2010-12-01 08:26:00 2010-12-09 20:01:00  22025

In [34]:
# Overall date range of the analysis dataset

print("First transaction:", sales_df['InvoiceDate'].min())
print("Last transaction:", sales_df['InvoiceDate'].max())
print("Total days:",
      (sales_df['InvoiceDate'].max() - sales_df['InvoiceDate'].min()).days)

First transaction: 2009-12-01 07:45:00
Last transaction: 2010-12-09 20:01:00
Total days: 373

In [35]:
# Top 10 products by net revenue

top_products = (
    sales_df.groupby(['StockCode', 'Description'])['Revenue']
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

display(top_products)

  StockCode                          Description    Revenue
0     22423             REGENCY CAKESTAND 3 TIER  162885.71
1    85123A   WHITE HANGING HEART T-LIGHT HOLDER  155540.37
2       DOT                       DOTCOM POSTAGE  116401.99
3     84879        ASSORTED COLOUR BIRD ORNAMENT   72251.32
4     22086      PAPER CHAIN KIT 50'S CHRISTMAS    57808.25
5    85099B              JUMBO BAG RED RETROSPOT   54217.92
6     47566                        PARTY BUNTING   49626.92
7     84347  ROTATING SILVER ANGELS T-LIGHT HLDR   47641.89
8      POST                              POSTAGE   46092.36
9    85099F                 JUMBO BAG STRAWBERRY   35823.39

In [36]:
# Revenue by country

country_revenue = (
    sales_df.groupby('Country')['Revenue']
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

display(country_revenue)

          Country      Revenue
0  United Kingdom  8298244.783
1            EIRE   352235.680
2     Netherlands   263861.760
3         Germany   195920.421
4          France   130661.550
5          Sweden    51190.110
6         Denmark    46972.950
7     Switzerland    43343.410
8           Spain    37052.130
9       Australia    30051.800

In [37]:
# Top 10 customers by net revenue

top_customers = (
    sales_df.dropna(subset=['Customer ID'])
    .groupby('Customer ID')['Revenue']
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

display(top_customers)

   Customer ID    Revenue
0      18102.0  341776.73
1      14646.0  243853.05
2      14156.0  183163.55
3      14911.0  137710.76
4      13694.0  128172.42
5      17511.0   83760.60
6      15061.0   82162.74
7      16684.0   75610.17
8      13089.0   55801.73
9      16754.0   54558.18

In [38]:
# Customer revenue concentration

customer_revenue = (
    sales_df.dropna(subset=['Customer ID'])
    .groupby('Customer ID')['Revenue']
    .sum()
    .sort_values(ascending=False)
)

top_10_revenue = customer_revenue.head(10).sum()
total_customer_revenue = customer_revenue.sum()
top_10_percentage = (top_10_revenue / total_customer_revenue) * 100

print("Total customer-attributed revenue: £{:,.2f}".format(total_customer_revenue))
print("Top 10 customers revenue: £{:,.2f}".format(top_10_revenue))
print("Top 10 customers revenue share: {:.2f}%".format(top_10_percentage))

Total customer-attributed revenue: £8,314,855.58
Top 10 customers revenue: £1,386,569.93
Top 10 customers revenue share: 16.68%

In [39]:
# Analyze cancellations / returns

returns = sales_df[sales_df['Quantity'] < 0].copy()
sales = sales_df[sales_df['Quantity'] > 0].copy()

return_value = returns['Revenue'].sum()
gross_sales_value = sales['Revenue'].sum()
net_revenue = sales_df['Revenue'].sum()

return_rate = len(returns) / len(sales_df) * 100
return_value_pct = abs(return_value) / gross_sales_value * 100

print("Positive sales revenue: £{:,.2f}".format(gross_sales_value))
print("Return/cancellation value: £{:,.2f}".format(return_value))
print("Net revenue: £{:,.2f}".format(net_revenue))
print("Return transaction rate: {:.2f}%".format(return_rate))
print("Return value as % of positive sales: {:.2f}%".format(return_value_pct))

Positive sales revenue: £10,272,136.23
Return/cancellation value: £-629,808.65
Net revenue: £9,642,327.58
Return transaction rate: 1.98%
Return value as % of positive sales: 6.13%

In [40]:
# Top 10 products by return/cancellation value

product_returns = (
    returns.groupby(['StockCode', 'Description'])['Revenue']
    .sum()
    .sort_values()
    .head(10)
    .reset_index()
)

display(product_returns)

      StockCode                        Description    Revenue
0             M                             Manual -277088.77
1     AMAZONFEE                         AMAZON FEE  -59491.12
2  BANK CHARGES                       Bank Charges  -26657.27
3             D                           Discount   -8186.21
4         22423           REGENCY CAKESTAND 3 TIER   -7027.05
5        79323W                WHITE CHERRY LIGHTS   -6277.30
6        79323P                 PINK CHERRY LIGHTS   -3967.35
7        84078A   SET/4 WHITE RETRO STORAGE CUBES    -3939.40
8         22138      BAKING SET 9 PIECE RETROSPOT    -3761.65
9         71477  COLOUR GLASS. STAR T-LIGHT HOLDER   -3730.25

In [41]:
# Identify non-product adjustment transactions

adjustment_codes = ['M', 'AMAZONFEE', 'BANK CHARGES', 'D', 'POST', 'DOT']

adjustments = returns[returns['StockCode'].isin(adjustment_codes)].copy()
product_returns = returns[~returns['StockCode'].isin(adjustment_codes)].copy()

print("Operational/financial adjustment value: £{:,.2f}".format(
    adjustments['Revenue'].sum()
))

print("Product-related return/cancellation value: £{:,.2f}".format(
    product_returns['Revenue'].sum()
))

print("Operational/financial adjustment rows:", len(adjustments))
print("Product-related return/cancellation rows:", len(product_returns))

Operational/financial adjustment value: £-376,914.23
Product-related return/cancellation value: £-252,894.42
Operational/financial adjustment rows: 541
Product-related return/cancellation rows: 9640

In [42]:
# Top 10 products by product-related return/cancellation value

top_product_returns = (
    product_returns.groupby(['StockCode', 'Description'])['Revenue']
    .sum()
    .sort_values()
    .head(10)
    .reset_index()
)

display(top_product_returns)

  StockCode                         Description  Revenue
0     22423            REGENCY CAKESTAND 3 TIER -7027.05
1    79323W                 WHITE CHERRY LIGHTS -6277.30
2    79323P                  PINK CHERRY LIGHTS -3967.35
3    84078A    SET/4 WHITE RETRO STORAGE CUBES  -3939.40
4     22138       BAKING SET 9 PIECE RETROSPOT  -3761.65
5     71477   COLOUR GLASS. STAR T-LIGHT HOLDER -3730.25
6     85220     SMALL FAIRY CAKE FRIDGE MAGNETS -3645.65
7         S                             SAMPLES -3090.21
8    85123A  WHITE HANGING HEART T-LIGHT HOLDER -2765.35
9   79323LP            LIGHT PINK CHERRY LIGHTS -2702.80

In [43]:
# Return rate for the top-selling products

product_sales = (
    sales[sales['StockCode'].isin(top_products['StockCode'])]
    .groupby(['StockCode', 'Description'])['Revenue']
    .sum()
)

product_return_value = (
    product_returns[product_returns['StockCode'].isin(top_products['StockCode'])]
    .groupby(['StockCode', 'Description'])['Revenue']
    .sum()
)

return_rate_top_products = pd.concat(
    [product_sales, product_return_value],
    axis=1
)

return_rate_top_products.columns = ['SalesRevenue', 'ReturnValue']
return_rate_top_products = return_rate_top_products.fillna(0)

return_rate_top_products['ReturnRate'] = (
    abs(return_rate_top_products['ReturnValue'])
    / return_rate_top_products['SalesRevenue']
    * 100
)

return_rate_top_products = (
    return_rate_top_products
    .sort_values('ReturnRate', ascending=False)
    .reset_index()
)

display(return_rate_top_products)

,StockCode,Description,SalesRevenue,ReturnValue,ReturnRate
0,22423,REGENCY CAKESTAND 3 TIER,169912.76,-7027.05,4.135681
1,85123A,WHITE HANGING HEART T-LIGHT HOLDER,158305.72,-2765.35,1.746841
2,84879,ASSORTED COLOUR BIRD ORNAMENT,72890.19,-638.87,0.876483
3,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,47954.49,-312.60,0.651868
4,22086,PAPER CHAIN KIT 50'S CHRISTMAS,58127.30,-319.05,0.548882
5,85099B,RED RETROSPOT JUMBO BAG,9563.89,-30.60,0.319953
6,85099B,JUMBO BAG RED RETROSPOT,54368.82,-150.90,0.277549
7,85099F,JUMBO BAG STRAWBERRY,35887.14,-63.75,0.177640
8,47566,PARTY BUNTING,49664.12,-37.20,0.074903
9,85099B,JUMBO BAG RED WHITE SPOTTY,25043.62,-10.80,0.043125
10,DOT,DOTCOM POSTAGE,116408.71,0.00,0.000000
11,POST,POSTAGE,49477.54,0.00,0.000000

In [44]:
# Export raw dataset for Google Sheets

df.to_csv('/content/Online_Retail_II_Raw.csv', index=False)

print("File created successfully.")
print("Rows:", len(df))
print("Columns:", len(df.columns))

File created successfully.
Rows: 525461
Columns: 8

In [45]:
import os

file_path = '/content/Online_Retail_II_Raw.csv'

size_mb = os.path.getsize(file_path) / (1024 * 1024)

print(f"File size: {size_mb:.2f} MB")

File size: 44.64 MB

In [46]:
# Split raw dataset into 2 parts for Google Sheets

part1 = df.iloc[:260000]
part2 = df.iloc[260000:]

part1.to_csv('/content/Online_Retail_II_Raw_Part1.csv', index=False)
part2.to_csv('/content/Online_Retail_II_Raw_Part2.csv', index=False)

print("Part 1 rows:", len(part1))
print("Part 2 rows:", len(part2))

Part 1 rows: 260000
Part 2 rows: 265461

In [47]:
# Split Part 2 into 3 smaller files

part2a = df.iloc[260000:350000]
part2b = df.iloc[350000:440000]
part2c = df.iloc[440000:]

part2a.to_csv('/content/Online_Retail_II_Raw_Part2A.csv', index=False)
part2b.to_csv('/content/Online_Retail_II_Raw_Part2B.csv', index=False)
part2c.to_csv('/content/Online_Retail_II_Raw_Part2C.csv', index=False)

print("Part 2A:", len(part2a))
print("Part 2B:", len(part2b))
print("Part 2C:", len(part2c))

Part 2A: 90000
Part 2B: 90000
Part 2C: 85461

In [48]:
#  Create analysis-ready processed dataset

df_processed = df.copy()

# 1. Remove exact duplicate rows
df_processed = df_processed.drop_duplicates().copy()

# 2. Create transaction value
df_processed['TotalAmount'] = (
    df_processed['Quantity'] * df_processed['Price']
)

# 3. Remove rows with missing description and zero price
df_processed = df_processed[
    ~(
        df_processed['Description'].isna() &
        (df_processed['Price'] == 0)
    )
].copy()

# 4. Remove negative-price accounting adjustments from sales analysis
#    (These are non-sales financial adjustments)
df_processed = df_processed[df_processed['Price'] >= 0].copy()

# 5. Create time-based fields
df_processed['Year'] = df_processed['InvoiceDate'].dt.year
df_processed['Month'] = df_processed['InvoiceDate'].dt.month
df_processed['MonthName'] = df_processed['InvoiceDate'].dt.strftime('%B')
df_processed['YearMonth'] = df_processed['InvoiceDate'].dt.to_period('M').astype(str)

print("Processed rows:", len(df_processed))
print("Processed columns:", len(df_processed.columns))
print("Remaining missing descriptions:", df_processed['Description'].isna().sum())
print("Remaining negative prices:", (df_processed['Price'] < 0).sum())

Processed rows: 515665
Processed columns: 13
Remaining missing descriptions: 0
Remaining negative prices: 0

In [49]:
#  Create sales analysis dataset

sales_df = df_processed[
    (df_processed['Price'] > 0) &
    (df_processed['Quantity'] != 0)
].copy()

# Revenue
sales_df['Revenue'] = (
    sales_df['Quantity'] * sales_df['Price']
)

print("Sales analysis rows:", len(sales_df))
print("Total net revenue: £{:,.2f}".format(sales_df['Revenue'].sum()))
print("Positive sales revenue: £{:,.2f}".format(
    sales_df.loc[sales_df['Quantity'] > 0, 'Revenue'].sum()
))
print("Negative transaction value: £{:,.2f}".format(
    sales_df.loc[sales_df['Quantity'] < 0, 'Revenue'].sum()
))

Sales analysis rows: 514912
Total net revenue: £9,642,327.58
Positive sales revenue: £10,272,136.23
Negative transaction value: £-629,808.65

In [50]:
import os

# Create output folder
os.makedirs('/content/assessment_outputs', exist_ok=True)

# 1. Monthly revenue
monthly_revenue = (
    sales_df.groupby('YearMonth')['Revenue']
    .sum()
    .reset_index()
)

# 2. Country revenue
country_revenue = (
    sales_df.groupby('Country')['Revenue']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

# 3. Top products
top_products_export = (
    sales_df.groupby(['StockCode', 'Description'])['Revenue']
    .sum()
    .sort_values(ascending=False)
    .head(20)
    .reset_index()
)

# 4. Top customers
top_customers_export = (
    sales_df.dropna(subset=['Customer ID'])
    .groupby('Customer ID')['Revenue']
    .sum()
    .sort_values(ascending=False)
    .head(20)
    .reset_index()
)

# 5. Product return/cancellation impact
product_returns_export = (
    product_returns
    .groupby(['StockCode', 'Description'])['Revenue']
    .sum()
    .sort_values()
    .head(20)
    .reset_index()
)

# 6. KPI summary
kpi_summary = pd.DataFrame({
    'Metric': [
        'Original rows',
        'Processed rows',
        'Sales analysis rows',
        'Net revenue',
        'Positive sales revenue',
        'Negative transaction value',
        'Customer-attributed revenue',
        'Top 10 customer revenue share'
    ],
    'Value': [
        len(df),
        len(df_processed),
        len(sales_df),
        sales_df['Revenue'].sum(),
        sales_df.loc[sales_df['Quantity'] > 0, 'Revenue'].sum(),
        sales_df.loc[sales_df['Quantity'] < 0, 'Revenue'].sum(),
        customer_revenue.sum(),
        top_10_percentage
    ]
})

# Export files
monthly_revenue.to_csv(
    '/content/assessment_outputs/monthly_revenue.csv', index=False
)

country_revenue.to_csv(
    '/content/assessment_outputs/country_revenue.csv', index=False
)

top_products_export.to_csv(
    '/content/assessment_outputs/top_products.csv', index=False
)

top_customers_export.to_csv(
    '/content/assessment_outputs/top_customers.csv', index=False
)

product_returns_export.to_csv(
    '/content/assessment_outputs/product_returns.csv', index=False
)

kpi_summary.to_csv(
    '/content/assessment_outputs/kpi_summary.csv', index=False
)

print("All analysis files exported successfully.")
print("\nFiles created:")
for file in os.listdir('/content/assessment_outputs'):
    print("-", file)

All analysis files exported successfully.

Files created:
- kpi_summary.csv
- top_customers.csv
- product_returns.csv
- country_revenue.csv
- top_products.csv
- monthly_revenue.csv

In [51]:
import shutil

# Create a ZIP file containing all assessment outputs
zip_path = shutil.make_archive(
    '/content/assessment_outputs',
    'zip',
    '/content/assessment_outputs'
)

print("ZIP created:")
print(zip_path)

ZIP created:
/content/assessment_outputs.zip